### PR TITLE
MODULE 2 : TODO LIST

### PR DESCRIPTION
**Pull request by Ntwali-Josue**
### In this Pull Request I: 
- Add a new JavaScript file and import it as a module and import/export it as a module
- Add event listener to the checkbox (change).
- Update items object's value for completed key upon user actions.
- Store the updated array of items in local storage, so the user gets the correct list values after the page reloads.
- Implement the CRUD methods to my todo tasks.
- Remove all hardcoded items from the tasks array.
- Implement a function for adding a new task (add a new element to the array).
- Implement a function for editing task descriptions.
- Implement a function for deleting a task (remove an element from the array).
- Implement a function for the "Clear all completed".

### CODE REVIEW

**Comment by enionsouza** [comment]
## Hello, @Ntwali-Josue!  :wave: 
Your project looks amazing! Good job!
There are however a few issues that you still need to work on ✍🏾  👨🏾‍💻:

- Great UI design. You made a pretty good use of Bootstrap ✔️ 
- Good ReadMe, but consider adding the steps the user needs to follow in order to make use of your code with `webpack` ✔️

## Required Changes ♻️
 💬 Check the comments under the review.

Cheers and Happy coding!👏 💻 🍷.

#### Regarding the best practices we are studying now, please, kindly consider the following issues:

- [ ] As the default practice for naming variables, please, consider changing the naming pattern from `Iscompleted` to `isCompleted`.
https://github.com/Ntwali-Josue/TODO_APP/blob/9104347775fe18a6d3deb3686cb9264283cfa978/src/index.js#L9
<br/><br/>

- [ ] This line apparently has no use in your code. Kindly, consider removing to comply with the best coding practices.
https://github.com/Ntwali-Josue/TODO_APP/blob/9104347775fe18a6d3deb3686cb9264283cfa978/src/index.js#L16
<br><br>

- [ ] To comply with the DRY principle, kindly consider using a function to avoid repetition in your code - `clearItem()` and `displayList()`
https://github.com/Ntwali-Josue/TODO_APP/blob/9104347775fe18a6d3deb3686cb9264283cfa978/src/index.js#L40-L41
https://github.com/Ntwali-Josue/TODO_APP/blob/9104347775fe18a6d3deb3686cb9264283cfa978/src/index.js#L58-L59
https://github.com/Ntwali-Josue/TODO_APP/blob/9104347775fe18a6d3deb3686cb9264283cfa978/src/index.js#L89-L90
<br><br>

**Comment by Ntwali-Josue** [comment]
> * [ ]  As the default practice for naming variables, please, consider changing the naming pattern from `Iscompleted` to `isCompleted`.
>   https://github.com/Ntwali-Josue/TODO_APP/blob/9104347775fe18a6d3deb3686cb9264283cfa978/src/index.js#L9

Thanks a lot, @enionsouza for point this out💯. As you can see here, I have updated my code by using the camelCase naming convention for my variables. You can use this [link](https://github.com/Ntwali-Josue/TODO_APP/pull/1/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R9) to see this change in detail.
image

**Comment by Ntwali-Josue** [comment]
> * [ ]  This line apparently has no use in your code. Kindly, consider removing to comply with the best coding practices.
>   https://github.com/Ntwali-Josue/TODO_APP/blob/9104347775fe18a6d3deb3686cb9264283cfa978/src/index.js#L16

**Thanks @enionsouza for mentioning this issue 💯 . As you see here, I have updated my file by removing this code ✍🏾 . You can see the change using this [link](https://github.com/Ntwali-Josue/TODO_APP/pull/1/commits/24614800fc8cbf95aa2d1f374fe0dcb8322f8352#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556L16) 👨🏾‍💻 
image

**Comment by Ntwali-Josue** [comment]
> * [ ]  To comply with the DRY principle, kindly consider using a function to avoid repetition in your code - `clearItem()` and `displayList()`
>   https://github.com/Ntwali-Josue/TODO_APP/blob/9104347775fe18a6d3deb3686cb9264283cfa978/src/index.js#L40-L41
>   
>   https://github.com/Ntwali-Josue/TODO_APP/blob/9104347775fe18a6d3deb3686cb9264283cfa978/src/index.js#L58-L59
>   
>   https://github.com/Ntwali-Josue/TODO_APP/blob/9104347775fe18a6d3deb3686cb9264283cfa978/src/index.js#L89-L90

Thanks @enionsouza for mentioning this issue 💯 . As you see here, I have updated my file by refactoring my code 👨🏾‍💻 . You can see the change using this [link](https://github.com/Ntwali-Josue/TODO_APP/pull/1/commits/24614800fc8cbf95aa2d1f374fe0dcb8322f8352#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R27-R63)

image

**Review by enionsouza — APPROVED** [review]
Hi @Ntwali-Josue, 
Your project is complete! It's time to merge it :shipit: 

### Congratulations! 🎉

Applauses!

#### Cheers and Happy coding!👏👏👏

**Comment by Ntwali-Josue** [comment]
Thanks @enionsouza 🥂

**Pull request merged**
